name: Docs generator

on:
  repository_dispatch:
    types: [ 'release-publish' ]
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repo'
        required: true
        type: string
      builder_name:
        description: 'Builder script name'
        required: true
        type: string
      release_version:
        description: 'Release version'
        required: true
        type: string


permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: "builder_name-${{ github.event.client_payload.builder_name || github.event.inputs.builder_name }}-"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Extract vars
      id: extract-vars
      run: |
        echo ">>>> inputs ${{ github.event.inputs }}"
        echo ">>>> client_payload ${{ github.event.client_payload }}"
        if [ "${{ github.event_name }}" == "repository_dispatch" ]
        action_pass="yes"
        then
          echo "SOURCE_REPO=${{ github.event.client_payload.source_repo }}" >> $GITHUB_ENV
          echo "BUILDER_NAME=${{ github.event.client_payload.builder_name }}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${{ github.event.client_payload.release_version }}" >> $GITHUB_ENV
        elif [ "${{ github.event_name }}" == "workflow_dispatch" ]
        then
          echo "SOURCE_REPO=${{ github.event.inputs.source_repo }}" >> $GITHUB_ENV
          echo "BUILDER_NAME=${{ github.event.inputs.builder_name }}" >> $GITHUB_ENV
          echo "SOURCE_TAG=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV
        else
          action_pass="no"
          echo ">>>> BAD INPUT"
        fi
        echo "ACTION_PASS=${action_pass}" >> $GITHUB_ENV
    - name: Run generator
      if: "${{ env.ACTION_PASS }} == 'yes'"
      id: run-generator
      uses: maxhr/near--docs-generator@HEAD
      with:
        source_repo: ${{ env.source_repo }}
        builder_name: ${{ env.builder_name }}
        release_version: ${{ env.release_version }}
