name: Docs generator

on:
  repository_dispatch:
    types: [ 'near-api-js', 'near-cli', 'near-sdk-js' ]
  workflow_dispatch:
    inputs:
      docs_source:
        description: 'Source repo'
        required: true
        type: choice
        options:
          - 'near-api-js'
          - 'near-cli'
          - 'near-sdk-js'
      release_version:
        description: 'Release version'
        required: true
        type: string

permissions: write-all

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: docs-generator
        uses: maxhr/near--docs-generator@HEAD
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docs_source: ${{ inputs.docs_source }}
          release_version: ${{ inputs.release_version }}
