name: Docs generator

on:
  repository_dispatch:
    types: [ 'release-publish' ]
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repo'
        required: true
        type: string
      builder_name:
        description: 'Builder script name'
        required: true
        type: string
      release_version:
        description: 'Release version'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  publish-from-dispatch:
    if: ${{ github.event_name == 'repository_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - name: docs-generator
      uses: maxhr/near--docs-generator@HEAD
      with:
        github_token: ${{ github.token }}
        source_repo: ${{ github.event.client_payload.source_repo }}
        builder_name: ${{ github.event.client_payload.builder_name }}
        release_version: ${{ github.event.client_payload.release_version }}
  publish-form-manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
    - name: docs-generator
      uses: maxhr/near--docs-generator@HEAD
      with:
        github_token: ${{ github.token }}
        source_repo: ${{ inputs.source_repo }}
        builder_name: ${{ inputs.builder_name }}
        release_version: ${{ inputs.release_version }}
